In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Book1.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

print(X)
print(y)

[['Mie' 44.0 72000.0]
 ['Bakso' 27.0 48000.0]
 ['Mie' 30.0 54000.0]
 ['Gudeg' 38.0 61000.0]
 ['Sate' 40.0 nan]
 ['Gudeg' 35.0 58000.0]
 ['Sate' nan 52000.0]
 ['Bakso' 48.0 79000.0]
 ['Sate' 50.0 83000.0]
 ['Bakso' 37.0 67000.0]
 ['Bakso' 50.0 38000.0]
 ['Mie' 10.0 43000.0]
 ['Gudeg' 34.0 69000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No']


In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

print(X)

[['Mie' 44.0 72000.0]
 ['Bakso' 27.0 48000.0]
 ['Mie' 30.0 54000.0]
 ['Gudeg' 38.0 61000.0]
 ['Sate' 40.0 60333.333333333336]
 ['Gudeg' 35.0 58000.0]
 ['Sate' 36.916666666666664 52000.0]
 ['Bakso' 48.0 79000.0]
 ['Sate' 50.0 83000.0]
 ['Bakso' 37.0 67000.0]
 ['Bakso' 50.0 38000.0]
 ['Mie' 10.0 43000.0]
 ['Gudeg' 34.0 69000.0]]


In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

[[0.0 0.0 1.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 40.0 60333.333333333336]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 36.916666666666664 52000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 1.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 0.0 50.0 38000.0]
 [0.0 0.0 1.0 0.0 10.0 43000.0]
 [0.0 1.0 0.0 0.0 34.0 69000.0]]


In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[0 1 0 0 1 1 0 1 0 1 1 1 0]


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[1.0 0.0 0.0 0.0 50.0 38000.0]
 [1.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 1.0 36.916666666666664 52000.0]
 [0.0 0.0 1.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 34.0 69000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 1.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 10.0 43000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]
[[0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 40.0 60333.333333333336]]
[1 1 0 0 1 0 1 0 1 1]
[0 0 1]


In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

print(X_train)
print(X_test)

[[1.0 0.0 0.0 -0.49999999999999994 1.1025129970907066 -1.565082701305981]
 [1.0 0.0 0.0 -0.49999999999999994 -0.8772761193506398
  -0.8816404736614478]
 [0.0 0.0 0.0 1.9999999999999998 -0.02367139160962467 -0.6082635826036346]
 [0.0 0.0 1.0 -0.49999999999999994 0.5860462710625293 0.7586208726854319]
 [1.0 0.0 0.0 -0.49999999999999994 0.9303574217479809 1.237030432036605]
 [0.0 1.0 0.0 -0.49999999999999994 -0.27473160565109955
  0.5535882043920719]
 [1.0 0.0 0.0 -0.49999999999999994 -0.01649824263701089
  0.41689975886316527]
 [0.0 0.0 0.0 1.9999999999999998 1.1025129970907066 1.5104073230944184]
 [0.0 0.0 1.0 -0.49999999999999994 -2.340598509763809 -1.2233615874837145]
 [0.0 1.0 0.0 -0.49999999999999994 -0.18865381797973665
  -0.19819824601691463]]
[[0.0 0.0 1.0 -0.49999999999999994 -0.619042756336551 -0.4715751370747279]
 [0.0 1.0 0.0 -0.49999999999999994 0.06957954503435199
  0.006834422276445332]
 [0.0 0.0 0.0 1.9999999999999998 0.24173512037707776 -0.03872839289985672]]
